# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  # Ruff - 現代化的 Python linter 和 formatter (比 flake8 + isort 更快)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      # Linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Formatter (可替代 black + isort)
      - id: ruff-format

  # Black - Python 代碼格式化工具 (與 ruff-format 二選一)
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.13
        args: ["--line-length=88"]

  # isort - 導入語句排序 (與 ruff 的 I 規則二選一)
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile=black", "--line-length=88"]

  # 基本文件檢查
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
      - id: check-ast
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      # 防止直接提交到主分支 (暫時停用)
      # - id: no-commit-to-branch
      #   args: ['--branch', 'main', '--branch', 'master']

  # Flake8 - Python 代碼檢查 (暫時停用，ruff 已涵蓋大部分功能)
  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.2.0
  #   hooks:
  #     - id: flake8
  #       additional_dependencies: [flake8-docstrings, flake8-bugbear]
  #       args: ["--max-line-length=88", "--extend-ignore=E203,W503"]

  # MyPy - 靜態類型檢查 (暫時停用)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.16.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: ["types-click", "types-requests"]
  #       args: ["--ignore-missing-imports"]

  # Bandit - 安全問題檢查
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  # Prettier - 格式化 Markdown, YAML, JSON 等文件
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, markdown, json]
        exclude: 'uv\.lock'

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
